<?php

$target_cities_raw = [
    "Achhnera",
    "Afzalgarh",
    "Agra",
    "Ahraura",
    "Ayodhya",
    "Akbarpur",
    "Prayagraj Allahabad",
    "Allahganj",
    "Aliganj",
    "Aligarh",
    "Ambahta",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Amanpur",
    "Anandnagar",
    "Antu",
    "Anupshahr",
    "Aonla",
    "Atarra",
    "Atraulia",
    "Atrauli",
    "Auraiya",
    "Auras",
    "Azamgarh",
    "Baberu",
    "Babrala",
    "Babugarh",
    "Babina",
    "Bachhraon",
    "Bachhrawan",
    "Baghpat",
    "Baheri",
    "Bahjoi",
    "Bahraich",
    "Bahraigh",
    "Bahsuma",
    "Bahua",
    "Bakewar",
    "Baldev",
    "Ballia",
    "Balrampur",
    "Banat",
    "Banbasa",
    "Baraut",
    "Bareilly",
    "Barkhera Kalan",
    "Barsana",
    "Baragaon",
    "Basti",
    "Behat",
    "Bela",
    "Beniganj",
    "Beswan",
    "Bewar",
    "Bhadohi",
    "Bhagwantnagar",
    "Bharthana",
    "Bharwari",
    "Bhinga",
    "Bhongaon",
    "Bidhuna",
    "Bijnor",
    "Bilariaganj",
    "Bilgram",
    "Bilhaur",
    "Bilsanda",
    "Bilsi",
    "Bilthra",
    "Bilari",
    "Bindki",
    "Bisauli",
    "Bisenda Buzurg",
    "Bishunpur Urf Maharajganj",
    "Biswan",
    "Bithur",
    "Budaun",
    "Budhana",
    "Bulandshahr",
    "Bah",
    "Bajna",
    "Banda",
    "Bangarmau",
    "Bansdih",
    "Bansgaon",
    "Bansi",
    "Bara Banki",
    "Bighapur Khurd",
    "Bikapur",
    "Bilaspur",
    "Bisalpur",
    "Captainganj",
    "Chail",
    "Chakia",
    "Chandauli",
    "Chandauli District",
    "Chanduasi",
    "Charkhari",
    "Charthawal",
    "Chhaprauli",
    "Chharra",
    "Chhibramau",
    "Chhutmalpur",
    "Chhata",
    "Chillupar",
    "Chirgaon",
    "Chitrakoot",
    "Chopan",
    "Chunar",
    "Chandpur",
    "Colonelganj",
    "Dalmau",
    "Dankaur",
    "Daurala",
    "Dayal Bagh",
    "Deoband",
    "Deoranian",
    "Deoria",
    "Dewa",
    "Dhanaura",
    "Dhaurahra",
    "Dhampur",
    "Dibai",
    "Dohrighat",
    "Dostpur",
    "Dadri",
    "Dasna",
    "Dataganj",
    "Dudhi",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farah",
    "Farrukhabad",
    "Faridnagar",
    "Faridpur",
    "Fatehganj West",
    "Fatehgarh",
    "Fatehpur",
    "Fatehpur Chaurasi",
    "Fatehpur Sikri",
    "Fatehabad",
    "Firozabad",
    "Fyzabad",
    "Gajraula",
    "Gangoh",
    "Ganj Dundwara",
    "Ganj Muradabad",
    "Garautha",
    "Garhi Pukhta",
    "Garhmuktesar",
    "Gautam Buddha Nagar",
    "Gawan",
    "Ghazipur",
    "Ghiror",
    "Ghorawal",
    "Ghosi",
    "Ghatampur",
    "Ghaziabad",
    "Gohand",
    "Gokul",
    "Gola Bazar",
    "Gola Gokarannath",
    "Gonda",
    "Gonda City",
    "Gopamau",
    "Gorakhpur",
    "Goshainganj",
    "Govardhan",
    "Gulaothi",
    "Gunnaur",
    "Gursahaiganj",
    "Gursarai",
    "Gyanpur",
    "Haldaur",
    "Hamirpur",
    "Handia",
    "Haraiya",
    "Hardoi",
    "Harduaganj",
    "Hasanpur",
    "Hastinapur",
    "Hapur",
    "Hathras",
    "Hata",
    "Iglas",
    "Ikauna",
    "Indergarh",
    "Islamnagar",
    "Itaunja",
    "Itimadpur",
    "Jagdishpur",
    "Jagnair",
    "Jahangirpur",
    "Jahangirabad",
    "Jahanabad",
    "Jainpur",
    "Jais",
    "Jalesar",
    "Jalalpur",
    "Jalalabad",
    "Jalali",
    "Jarwal",
    "Jasrana",
    "Jaswantnagar",
    "Jaunpur",
    "Jewar",
    "Jhinjhana",
    "Jhalu",
    "Jhansi",
    "Jhinjhak",
    "Jhusi",
    "Jyotiba Phule Nagar",
    "Jalaun",
    "Jansath",
    "Kabrai",
    "Kachhwa",
    "Kadaura",
    "Kaimganj",
    "Kairana",
    "Kakrala",
    "Kamalganj",
    "Kampil",
    "Kannauj",
    "Kanpur",
    "Kanpur Dehat",
    "Karhal",
    "Karari",
    "Katra",
    "Kaushambi District",
    "Kemri",
    "Khada",
    "Khair",
    "Khairabad",
    "Khalilabad",
    "Kharela",
    "Khargupur",
    "Kharkhauda",
    "Khatauli",
    "Khekra",
    "Kheri",
    "Khudaganj",
    "Khurja",
    "Khaga",
    "Khanpur",
    "Khutar",
    "Kiraoli",
    "Kirakat",
    "Kishanpur",
    "Kishni",
    "Kithor",
    "Konch",
    "Kopaganj",
    "Kosi",
    "Kota",
    "Kotra",
    "Kulpahar",
    "Kunda",
    "Kundarkhi",
    "Kurara",
    "Kushinagar",
    "Kadipur",
    "Kakori",
    "Kalpi",
    "Kalinagar",
    "Kandhla",
    "Kant",
    "Kanth",
    "Kasganj",
    "Kiratpur",
    "Lakhna",
    "Lakhimpur",
    "Lalitpur",
    "Lar",
    "Loni",
    "Lucknow",
    "Lucknow District",
    "Laharpur",
    "Lalganj",
    "Lawar Khas",
    "Machhlishahr",
    "Maghar",
    "Maharajganj",
    "Mahmudabad",
    "Mahoba",
    "Maholi",
    "Mahroni",
    "Mahaban",
    "Mailani",
    "Mainpuri",
    "Malihabad",
    "Mandawar",
    "Maniar",
    "Manjhanpur",
    "Mankapur",
    "Mariahu",
    "Mataundh",
    "Mathura",
    "Mau",
    "Mau Aimma",
    "Maudaha",
    "Mauranwan",
    "Mawana",
    "Meerut",
    "Mehnagar",
    "Mehndawal",
    "Milak",
    "Mirzapur",
    "Misrikh",
    "Mohanpur",
    "Mohan",
    "Moradabad",
    "Moth",
    "Mubarakpur",
    "Mughal Sarai",
    "Muhammadabad",
    "Mursan",
    "Muradnagar",
    "Musafir-Khana",
    "Muzaffarnagar",
    "Madhoganj",
    "Madhogarh",
    "Manikpur",
    "Marahra",
    "Mirganj",
    "Miranpur",
    "Miranpur Katra",
    "Nadigaon",
    "Nagram",
    "Nagina",
    "Najibabad",
    "Nakur",
    "Nanauta",
    "Nandgaon",
    "Narauli",
    "Naraura",
    "Nautanwa",
    "Nawabganj",
    "Nichlaul",
    "Nihtaur",
    "Niwari",
    "Nizamabad",
    "Nanpara",
    "Nurpur",
    "Obra",
    "Orai",
    "Oran",
    "Pachperwa",
    "Padrauna",
    "Pahasu",
    "Palia Kalan",
    "Parshadepur",
    "Parichhatgarh",
    "Patiali",
    "Patti",
    "Pawayan",
    "Phalauda",
    "Phaphund",
    "Phariha",
    "Phulpur",
    "Pihani",
    "Pilkhua",
    "Pinahat",
    "Pipraich",
    "Pratapgarh",
    "Pukhrayan",
    "Purwa",
    "Pali",
    "Parichha",
    "Pilibhit",
    "Puranpur"
];

// Clean and normalize target list
$target_cities = [];
foreach ($target_cities_raw as $c) {
    $c = trim($c);
    if (!empty($c)) {
        $target_cities[$c] = true;
    }
}

echo "Target cities count: " . count($target_cities) . "\n";

$filepath = __DIR__ . '/../application/modules/packers_movers/views/data/uttar-pradesh.php';
if (!file_exists($filepath)) {
    die("File not found: $filepath\n");
}

// Backup file first
copy($filepath, $filepath . '.bak');
echo "Backup created.\n";

$lines = file($filepath);
$new_lines = [];
$processed_cities = [];

foreach ($lines as $line) {
    // Check if line contains an array entry: array('nm' => 'CityName',...
    if (preg_match('/(array\(\s*\'nm\'\s*=>\s*\'([^\']+)\')/', $line, $matches)) {
        $city_name = $matches[2];
        $processed_cities[$city_name] = true;
        
        // Check if this city is in our target list
        if (isset($target_cities[$city_name])) {
            // It should be active (uncommented). If it starts with //, remove it.
            $cleaned_line = preg_replace('/^\s*\/\/\s*/', "\t\t", $line);
            $new_lines[] = $cleaned_line;
        } else {
            // It should be inactive (commented out). If it doesn't start with //, comment it out.
            if (!preg_match('/^\s*\/\//', $line)) {
                $cleaned_line = preg_replace('/^(\s*)/', '$1// ', $line);
                $new_lines[] = $cleaned_line;
            } else {
                $new_lines[] = $line;
            }
        }
    } else {
        $new_lines[] = $line;
    }
}

// Find any target cities that were not in the file
$missing_cities = array_diff_key($target_cities, $processed_cities);
echo "Missing cities count: " . count($missing_cities) . "\n";

if (!empty($missing_cities)) {
    // Find the closing parenthesis line '):' or ');'
    $closing_idx = -1;
    for ($i = count($new_lines) - 1; $i >= 0; $i--) {
        if (trim($new_lines[$i]) === ');') {
            $closing_idx = $i;
            break;
        }
    }
    
    if ($closing_idx !== -1) {
        $added_lines = [];
        foreach ($missing_cities as $city_name => $_) {
            $added_lines[] = "\t\tarray('nm' => '$city_name','lat' => '0.00000000','lon' => '0.00000000','sc' => 'UP'),\n";
            echo "Adding missing city: $city_name\n";
        }
        
        // Insert missing cities before the closing array line
        array_splice($new_lines, $closing_idx, 0, $added_lines);
    } else {
        echo "Error: Could not find closing array parenthesis ');'\n";
    }
}

file_put_contents($filepath, implode('', $new_lines));
echo "Successfully updated $filepath\n";
