<?php

$target_cities_raw = [
    "Ahmedpur",
    "Aistala",
    "Aknapur",
    "Alipurduar",
    "Amta",
    "Amtala",
    "Andal",
    "Arambagh",
    "Asansol",
    "Ashoknagar Kalyangarh",
    "Badkulla",
    "Baduria",
    "Bagdogra",
    "Bagnan",
    "Bagula",
    "Bahula",
    "Baidyabati",
    "Bakreswar",
    "Balarampur",
    "Bally",
    "Balurghat",
    "Bamangola",
    "Baneswar",
    "Bangaon",
    "Bankra",
    "Bankura",
    "Bansberia",
    "Bansihari",
    "Barabazar",
    "Baranagar",
    "Barasat",
    "Bardhaman",
    "Barjora",
    "Barrackpore",
    "Baruipur",
    "Basanti",
    "Basirhat",
    "Begampur",
    "Belda",
    "Beldanga",
    "Beliatore",
    "Berhampore",
    "Bhadreswar",
    "Bhandardaha",
    "Bhatpara",
    "Birbhum",
    "Birpara",
    "Bishnupur",
    "Bolpur",
    "Budge Budge",
    "Bali Chak",
    "Bawali",
    "Canning",
    "Chakapara",
    "Chakdaha",
    "Champadanga",
    "Champdani",
    "Chandannagar",
    "Chandrakona",
    "Chittaranjan",
    "Churulia",
    "Champahati",
    "Contai",
    "Cooch Behar",
    "Cossimbazar",
    "Dakshin Dinajpur",
    "Dalkola",
    "Dum Dum",
    "Darjeeling",
    "Daulatpur",
    "Debagram",
    "Debipur",
    "Dhaniakhali",
    "Dhulagari",
    "Dhulian",
    "Dhupguri",
    "Diamond Harbour",
    "Digha",
    "Dinhata",
    "Domjur",
    "Dubrajpur",
    "Durgapur",
    "Egra",
    "Falakata",
    "Farakka",
    "Fort Gloster",
    "Gaighata",
    "Gairkata",
    "Gangadharpur",
    "Gangarampur",
    "Garui",
    "Garulia",
    "Ghatal",
    "Giria",
    "Gobardanga",
    "Gobindapur",
    "Gopinathpur",
    "Gopalpur",
    "Gorubathan",
    "Gosaba",
    "Gosanimari",
    "Gurdaha",
    "Guskhara",
    "Habra",
    "Haldia",
    "Haldibari",
    "Halisahar",
    "Harindanga",
    "Haringhata",
    "Haripur",
    "Hasimara",
    "Hindusthan Cables Town",
    "Hooghly",
    "Howrah",
    "Ichapur",
    "Indpur",
    "Ingraj Bazar",
    "Islampur",
    "Jafarpur",
    "Jaigaon",
    "Jalpaiguri",
    "Jamuria",
    "Jangipur",
    "Jaynagar Majilpur",
    "Jejur",
    "Jhalida",
    "Jhargram",
    "Jhilimili",
    "Kakdwip",
    "Kalaikunda",
    "Kaliaganj",
    "Kalimpong",
    "Kalna",
    "Kalyani",
    "Kamarhati",
    "Kamarpukur",
    "Kanchrapara",
    "Kandi",
    "Karimpur",
    "Katwa",
    "Kenda",
    "Keshabpur",
    "Kharagpur",
    "Kharar",
    "Kharba",
    "Khardaha",
    "Khatra",
    "Kirnahar",
    "Kolkata",
    "Konnagar",
    "Krishna Nagar",
    "Krishnapur",
    "Kshirpai",
    "Kulpi",
    "Kultali",
    "Kulti",
    "Kurseong",
    "Lalgarh",
    "Lalgola",
    "Loyabad",
    "Madanpur",
    "Madhyamgram",
    "Mahiari",
    "Mahishadal",
    "Mainaguri",
    "Manikpara",
    "Masila",
    "Mathabhanga",
    "Matiali",
    "Matigara",
    "Medinipur",
    "Mejia",
    "Memari",
    "Mirik",
    "Mohanpur",
    "Monoharpur",
    "Muragacha",
    "Muri",
    "Murshidabad",
    "Nabadwip",
    "Nabagram",
    "Nadia",
    "Nagarukhra",
    "Nagrakata",
    "Naihati",
    "Naksalbari",
    "Nalhati",
    "Nalpur",
    "Namkhana",
    "Nandigram",
    "Nangi",
    "Nayagram",
    "North 24 Parganas",
    "Odlabari",
    "Paikpara",
    "Panagarh",
    "Panchla",
    "Panchmura",
    "Pandua",
    "Panihati",
    "Panskura",
    "Parbatipur",
    "Paschim Medinipur",
    "Patiram",
    "Patuli",
    "Pujali",
    "Puncha",
    "Purba Medinipur",
    "Purulia",
    "Patrasaer",
    "Raghudebbati",
    "Raghunathpur",
    "Raiganj",
    "Rajmahal",
    "Rajnagar",
    "Ramchandrapur",
    "Ramjibanpur",
    "Rampur Hat",
    "Ranaghat",
    "Raniganj",
    "Raypur",
    "Rishra",
    "Ramnagar",
    "Sahapur",
    "Sainthia",
    "Salanpur",
    "Sankarpur",
    "Sankrail",
    "Santipur",
    "Santoshpur",
    "Santuri",
    "Sarenga",
    "Serampore",
    "Serpur",
    "Shyamnagar",
    "Siliguri",
    "Singur",
    "Sodpur",
    "Solap",
    "Sonada",
    "Sonamukhi",
    "Sonarpur",
    "South 24 Parganas",
    "Srikhanda",
    "Srirampur",
    "Suri",
    "Swarupnagar",
    "Takdah",
    "Taki",
    "Tamluk",
    "Tarakeswar",
    "Titagarh",
    "Tufanganj",
    "Tulin",
    "Uchalan",
    "Ula",
    "Uluberia",
    "Uttar Dinajpur",
    "Uttarpara Kotrung",
    "Amlagora"
];

// Clean and normalize target list
$target_cities = [];
foreach ($target_cities_raw as $c) {
    $c = trim($c);
    if (!empty($c)) {
        $target_cities[$c] = true;
    }
}

// Load the updated file and extract its active cities
$filepath = __DIR__ . '/../application/modules/packers_movers/views/data/west-bengal.php';
include $filepath; // Sets $cities array

if (!isset($cities) || !is_array($cities)) {
    die("Error: \$cities array not found or not an array.\n");
}

$active_cities = [];
foreach ($cities as $entry) {
    if (isset($entry['nm'])) {
        $active_cities[$entry['nm']] = true;
    }
}

echo "Active cities in file: " . count($active_cities) . "\n";
echo "Target cities: " . count($target_cities) . "\n";

$extra_active = array_diff_key($active_cities, $target_cities);
$missing_active = array_diff_key($target_cities, $active_cities);

$failed = false;

if (!empty($extra_active)) {
    echo "FAIL: Extra cities active in file:\n";
    foreach ($extra_active as $name => $_) {
        echo " - $name\n";
    }
    $failed = true;
}

if (!empty($missing_active)) {
    echo "FAIL: Missing active cities in file:\n";
    foreach ($missing_active as $name => $_) {
        echo " - $name\n";
    }
    $failed = true;
}

if (!$failed) {
    echo "SUCCESS: The active cities list matches the target list exactly (260 cities)!\n";
} else {
    exit(1);
}
