<?php

$target_cities_raw = [
    "Achhnera",
    "Afzalgarh",
    "Agra",
    "Ahraura",
    "Ayodhya",
    "Akbarpur",
    "Prayagraj Allahabad",
    "Allahganj",
    "Aliganj",
    "Aligarh",
    "Ambahta",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Amanpur",
    "Anandnagar",
    "Antu",
    "Anupshahr",
    "Aonla",
    "Atarra",
    "Atraulia",
    "Atrauli",
    "Auraiya",
    "Auras",
    "Azamgarh",
    "Baberu",
    "Babrala",
    "Babugarh",
    "Babina",
    "Bachhraon",
    "Bachhrawan",
    "Baghpat",
    "Baheri",
    "Bahjoi",
    "Bahraich",
    "Bahraigh",
    "Bahsuma",
    "Bahua",
    "Bakewar",
    "Baldev",
    "Ballia",
    "Balrampur",
    "Banat",
    "Banbasa",
    "Baraut",
    "Bareilly",
    "Barkhera Kalan",
    "Barsana",
    "Baragaon",
    "Basti",
    "Behat",
    "Bela",
    "Beniganj",
    "Beswan",
    "Bewar",
    "Bhadohi",
    "Bhagwantnagar",
    "Bharthana",
    "Bharwari",
    "Bhinga",
    "Bhongaon",
    "Bidhuna",
    "Bijnor",
    "Bilariaganj",
    "Bilgram",
    "Bilhaur",
    "Bilsanda",
    "Bilsi",
    "Bilthra",
    "Bilari",
    "Bindki",
    "Bisauli",
    "Bisenda Buzurg",
    "Bishunpur Urf Maharajganj",
    "Biswan",
    "Bithur",
    "Budaun",
    "Budhana",
    "Bulandshahr",
    "Bah",
    "Bajna",
    "Banda",
    "Bangarmau",
    "Bansdih",
    "Bansgaon",
    "Bansi",
    "Bara Banki",
    "Bighapur Khurd",
    "Bikapur",
    "Bilaspur",
    "Bisalpur",
    "Captainganj",
    "Chail",
    "Chakia",
    "Chandauli",
    "Chandauli District",
    "Chanduasi",
    "Charkhari",
    "Charthawal",
    "Chhaprauli",
    "Chharra",
    "Chhibramau",
    "Chhutmalpur",
    "Chhata",
    "Chillupar",
    "Chirgaon",
    "Chitrakoot",
    "Chopan",
    "Chunar",
    "Chandpur",
    "Colonelganj",
    "Dalmau",
    "Dankaur",
    "Daurala",
    "Dayal Bagh",
    "Deoband",
    "Deoranian",
    "Deoria",
    "Dewa",
    "Dhanaura",
    "Dhaurahra",
    "Dhampur",
    "Dibai",
    "Dohrighat",
    "Dostpur",
    "Dadri",
    "Dasna",
    "Dataganj",
    "Dudhi",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farah",
    "Farrukhabad",
    "Faridnagar",
    "Faridpur",
    "Fatehganj West",
    "Fatehgarh",
    "Fatehpur",
    "Fatehpur Chaurasi",
    "Fatehpur Sikri",
    "Fatehabad",
    "Firozabad",
    "Fyzabad",
    "Gajraula",
    "Gangoh",
    "Ganj Dundwara",
    "Ganj Muradabad",
    "Garautha",
    "Garhi Pukhta",
    "Garhmuktesar",
    "Gautam Buddha Nagar",
    "Gawan",
    "Ghazipur",
    "Ghiror",
    "Ghorawal",
    "Ghosi",
    "Ghatampur",
    "Ghaziabad",
    "Gohand",
    "Gokul",
    "Gola Bazar",
    "Gola Gokarannath",
    "Gonda",
    "Gonda City",
    "Gopamau",
    "Gorakhpur",
    "Goshainganj",
    "Govardhan",
    "Gulaothi",
    "Gunnaur",
    "Gursahaiganj",
    "Gursarai",
    "Gyanpur",
    "Haldaur",
    "Hamirpur",
    "Handia",
    "Haraiya",
    "Hardoi",
    "Harduaganj",
    "Hasanpur",
    "Hastinapur",
    "Hapur",
    "Hathras",
    "Hata",
    "Iglas",
    "Ikauna",
    "Indergarh",
    "Islamnagar",
    "Itaunja",
    "Itimadpur",
    "Jagdishpur",
    "Jagnair",
    "Jahangirpur",
    "Jahangirabad",
    "Jahanabad",
    "Jainpur",
    "Jais",
    "Jalesar",
    "Jalalpur",
    "Jalalabad",
    "Jalali",
    "Jarwal",
    "Jasrana",
    "Jaswantnagar",
    "Jaunpur",
    "Jewar",
    "Jhinjhana",
    "Jhalu",
    "Jhansi",
    "Jhinjhak",
    "Jhusi",
    "Jyotiba Phule Nagar",
    "Jalaun",
    "Jansath",
    "Kabrai",
    "Kachhwa",
    "Kadaura",
    "Kaimganj",
    "Kairana",
    "Kakrala",
    "Kamalganj",
    "Kampil",
    "Kannauj",
    "Kanpur",
    "Kanpur Dehat",
    "Karhal",
    "Karari",
    "Katra",
    "Kaushambi District",
    "Kemri",
    "Khada",
    "Khair",
    "Khairabad",
    "Khalilabad",
    "Kharela",
    "Khargupur",
    "Kharkhauda",
    "Khatauli",
    "Khekra",
    "Kheri",
    "Khudaganj",
    "Khurja",
    "Khaga",
    "Khanpur",
    "Khutar",
    "Kiraoli",
    "Kirakat",
    "Kishanpur",
    "Kishni",
    "Kithor",
    "Konch",
    "Kopaganj",
    "Kosi",
    "Kota",
    "Kotra",
    "Kulpahar",
    "Kunda",
    "Kundarkhi",
    "Kurara",
    "Kushinagar",
    "Kadipur",
    "Kakori",
    "Kalpi",
    "Kalinagar",
    "Kandhla",
    "Kant",
    "Kanth",
    "Kasganj",
    "Kiratpur",
    "Lakhna",
    "Lakhimpur",
    "Lalitpur",
    "Lar",
    "Loni",
    "Lucknow",
    "Lucknow District",
    "Laharpur",
    "Lalganj",
    "Lawar Khas",
    "Machhlishahr",
    "Maghar",
    "Maharajganj",
    "Mahmudabad",
    "Mahoba",
    "Maholi",
    "Mahroni",
    "Mahaban",
    "Mailani",
    "Mainpuri",
    "Malihabad",
    "Mandawar",
    "Maniar",
    "Manjhanpur",
    "Mankapur",
    "Mariahu",
    "Mataundh",
    "Mathura",
    "Mau",
    "Mau Aimma",
    "Maudaha",
    "Mauranwan",
    "Mawana",
    "Meerut",
    "Mehnagar",
    "Mehndawal",
    "Milak",
    "Mirzapur",
    "Misrikh",
    "Mohanpur",
    "Mohan",
    "Moradabad",
    "Moth",
    "Mubarakpur",
    "Mughal Sarai",
    "Muhammadabad",
    "Mursan",
    "Muradnagar",
    "Musafir-Khana",
    "Muzaffarnagar",
    "Madhoganj",
    "Madhogarh",
    "Manikpur",
    "Marahra",
    "Mirganj",
    "Miranpur",
    "Miranpur Katra",
    "Nadigaon",
    "Nagram",
    "Nagina",
    "Najibabad",
    "Nakur",
    "Nanauta",
    "Nandgaon",
    "Narauli",
    "Naraura",
    "Nautanwa",
    "Nawabganj",
    "Nichlaul",
    "Nihtaur",
    "Niwari",
    "Nizamabad",
    "Nanpara",
    "Nurpur",
    "Obra",
    "Orai",
    "Oran",
    "Pachperwa",
    "Padrauna",
    "Pahasu",
    "Palia Kalan",
    "Parshadepur",
    "Parichhatgarh",
    "Patiali",
    "Patti",
    "Pawayan",
    "Phalauda",
    "Phaphund",
    "Phariha",
    "Phulpur",
    "Pihani",
    "Pilkhua",
    "Pinahat",
    "Pipraich",
    "Pratapgarh",
    "Pukhrayan",
    "Purwa",
    "Pali",
    "Parichha",
    "Pilibhit",
    "Puranpur"
];

// Clean and normalize target list
$target_cities = [];
foreach ($target_cities_raw as $c) {
    $c = trim($c);
    if (!empty($c)) {
        $target_cities[$c] = true;
    }
}

// Load the updated file and extract its active cities
$filepath = __DIR__ . '/../application/modules/packers_movers/views/data/uttar-pradesh.php';
include $filepath; // Sets $cities array

if (!isset($cities) || !is_array($cities)) {
    die("Error: \$cities array not found or not an array.\n");
}

$active_cities = [];
foreach ($cities as $entry) {
    if (isset($entry['nm'])) {
        $active_cities[$entry['nm']] = true;
    }
}

echo "Active cities in file: " . count($active_cities) . "\n";
echo "Target cities: " . count($target_cities) . "\n";

$extra_active = array_diff_key($active_cities, $target_cities);
$missing_active = array_diff_key($target_cities, $active_cities);

$failed = false;

if (!empty($extra_active)) {
    echo "FAIL: Extra cities active in file:\n";
    foreach ($extra_active as $name => $_) {
        echo " - $name\n";
    }
    $failed = true;
}

if (!empty($missing_active)) {
    echo "FAIL: Missing active cities in file:\n";
    foreach ($missing_active as $name => $_) {
        echo " - $name\n";
    }
    $failed = true;
}

if (!$failed) {
    echo "SUCCESS: The active cities list matches the target list exactly (371 cities)!\n";
} else {
    exit(1);
}
